#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rebootmgr
Version  : 0.20.1
Release  : 5
URL      : https://github.com/SUSE/rebootmgr/releases/download/v0.20.1/rebootmgr-0.20.1.tar.xz
Source0  : https://github.com/SUSE/rebootmgr/releases/download/v0.20.1/rebootmgr-0.20.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: rebootmgr-bin = %{version}-%{release}
Requires: rebootmgr-data = %{version}-%{release}
Requires: rebootmgr-license = %{version}-%{release}
Requires: rebootmgr-man = %{version}-%{release}
Requires: rebootmgr-services = %{version}-%{release}
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(libeconf)

%description
No detailed description available

%package bin
Summary: bin components for the rebootmgr package.
Group: Binaries
Requires: rebootmgr-data = %{version}-%{release}
Requires: rebootmgr-license = %{version}-%{release}
Requires: rebootmgr-services = %{version}-%{release}

%description bin
bin components for the rebootmgr package.


%package data
Summary: data components for the rebootmgr package.
Group: Data

%description data
data components for the rebootmgr package.


%package license
Summary: license components for the rebootmgr package.
Group: Default

%description license
license components for the rebootmgr package.


%package man
Summary: man components for the rebootmgr package.
Group: Default

%description man
man components for the rebootmgr package.


%package services
Summary: services components for the rebootmgr package.
Group: Systemd services

%description services
services components for the rebootmgr package.


%prep
%setup -q -n rebootmgr-0.20.1
cd %{_builddir}/rebootmgr-0.20.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1573534351
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static --libexecdir=/usr/lib
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1573534351
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rebootmgr
cp %{_builddir}/rebootmgr-0.20.1/COPYING %{buildroot}/usr/share/package-licenses/rebootmgr/3127907a7623734f830e8c69ccee03b693bf993e
cp %{_builddir}/rebootmgr-0.20.1/COPYING.LIB %{buildroot}/usr/share/package-licenses/rebootmgr/01a6b4bf79aca9b556822601186afab86e8c4fbf
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rebootmgrctl
/usr/bin/rebootmgrd

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/interfaces/org.opensuse.RebootMgr.xml
/usr/share/dbus-1/system.d/org.opensuse.RebootMgr.conf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rebootmgr/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/rebootmgr/3127907a7623734f830e8c69ccee03b693bf993e

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/rebootmgrctl.1
/usr/share/man/man5/rebootmgr.conf.5
/usr/share/man/man8/org.opensuse.RebootMgr.conf.8
/usr/share/man/man8/rebootmgr.service.8
/usr/share/man/man8/rebootmgrd.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/rebootmgr.service
